### PR TITLE
Add Backend Endpoints

### PR DESCRIPTION
**Pull request by Azure-Agst**
Added all of the public & protected (i.e. non-admin) endpoints as per our meeting notes. Also added a few QoL changes, like splitting our auth guard into two for protected and admin.

### CODE REVIEW

**Comment by ColeWarren** [comment]
> Added all of the public & protected (i.e. non-admin) endpoints as per our meeting notes. Also added a few QoL changes, like splitting our auth guard into two for protected and admin.

My bad, I did have the auth guard separate for protected and admin at the start but for some reason I though it would be better to combine them.

**Comment by Azure-Agst** [comment]
> I thought it would be better to combine them.

I split them in the sake of time, but now that i'm thinking about it... If we wanted to be really thorough, we could just design the guard itself with a kwarg `admin`, so the invocation would look like:
```py
@auth_guard()
def protected():
    pass

@auth_guard(admin=True)
def admins_only():
    pass
```

Regardless, what we have right now works.

**Comment by Azure-Agst** [comment]
I don't feel like tackling this actions-only testing bug is worth my time, so I'm gonna cheese it for now

**Review by stollerdaws — APPROVED** [review]
Looks great, good work on the admin page.

**Pull request merged**
